apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: iotdemo-config-map
  data:
    esf.hostname: 'http://ec-api-ROUTE-DOMAIN'
    esf.password: 'Infosys123!@#'
    esf.port: '80'
    esf.username: user8
    mariadb.database: sampledb
    mariadb.password: RirqCJ2bnpwQLQUI
    mariadb.port: '3306'
    mariadb.service: mariadb
    mariadb.username: userCQ3
    mqtt.hostname: ec-broker-mqtt-ROUTE-DOMAIN
    mqtt.machine.topic: +/+/cloudera-demo/facilities/+/lines/+/machines/machine-1
    mqtt.password: ec-password
    mqtt.payload.topic: iot-demo/data
    mqtt.port: '31891'
    mqtt.user.password: 'Infosys123!@#'
    mqtt.user.username: user8
    mqtt.username: ec-sys
    mqtt.websocket: ec-broker-ws-ROUTE-DOMAIN
    mqtt.websocket.port: '80'
- kind: ImageStream
  apiVersion: "v1"
  labels:
    app: s2i-java
  metadata:
    name: s2i-java
  spec:
    tags:
      - from:
          kind: DockerImage
          name: 'fabric8/s2i-java:2.3.1'
        name: '2.3.1'
        referencePolicy:
          type: Source
