apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: iotdemo-config-map
  data:
    esf.hostname: 'http://ec-api-${PROJECTID}.apps.infosys-3e7e.openshiftworkshop.com'
    esf.password: 'Infosys123!@#'
    esf.port: '80'
    esf.username: ${USERID}
    mariadb.database: ecdb
    mariadb.password: RedHat123
    mariadb.port: '3306'
    mariadb.service: mariadb
    mariadb.username: redhat
    mqtt.hostname: ec-broker-mqtt.${PROJECTID}.svc
    mqtt.machine.topic: +/+/cloudera-demo/facilities/+/lines/+/machines/machine-1
    mqtt.password: ec-password
    mqtt.payload.topic: iot-demo/data
    mqtt.port: ${MQTTPORT}
    mqtt.user.password: 'Infosys123!@#'
    mqtt.user.username: ${USERID}
    mqtt.username: ec-sys
    mqtt.websocket: ec-broker-ws-${PROJECTID}.apps.infosys-3e7e.openshiftworkshop.com
    mqtt.websocket.port: '80'
- kind: ImageStream
  apiVersion: "v1"
  labels:
    app: s2i-java
  metadata:
    name: s2i-java
  spec:
    tags:
      - from:
          kind: DockerImage
          name: 'fabric8/s2i-java:2.3.1'
        name: '2.3.1'
        referencePolicy:
          type: Source
parameters:
- description: The user name you are using for this workshop.
  displayName: User ID
  name: USERID
  required: true
- description: The default project name for your user.
  displayName: Project ID
  name: PROJECTID
  required: true
- description: The MQTT Port specific to your user.
  displayName: MQTT Port
  name: MQTTPORT
  required: true
